name: flutter_vonage_number_verification
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/breeze-social/flutter_vonage_number_verification
repository: https://github.com/breeze-social/flutter_vonage_number_verification
issue_tracker: https://github.com/breeze-social/flutter_vonage_number_verification/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_vonage_number_verification
        pluginClass: FlutterVonageNumberVerificationPlugin
      ios:
        pluginClass: FlutterVonageNumberVerificationPlugin
